baseURL = "http://jonathanwayy.xyz"
title = "Jonathan`s Blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字

theme = "LeaveIt"

paginate = 15 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
googleAnalytics = "" # Google 统计 id
Copyright = "All rights reserved - 2020"

preserveTaxonomyNames = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2020
    author = "Jonathan Wang"                          # Author's name
    avatar = "/images/me/avatar.jpg"           # Author's avatar
    subtitle = "nuqneH."                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = false # gitalk 评论系统

    google_verification = ""

    description = "" # (Meta) 描述
    keywords = "" # site keywords
    
    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    Github  = "JonnieWayy"
    Email   = "zijiewang9928@gmail.com"
    Wechat = "/images/me/wechat.png"
    Telegram = "+8618851901683"
